// Generated by dts-bundle v0.7.2

declare module 'hello-world-npm-module' {
    export { HelloEarthService } from 'hello-world-npm-module/hello-earth.service';
    export { IHelloWorldService } from 'hello-world-npm-module/hello-world-interface.service';
    export { HelloWorldService } from 'hello-world-npm-module/hello-world.service';
}

declare module 'hello-world-npm-module/hello-earth.service' {
    import { IHelloWorldService } from 'hello-world-npm-module/hello-world-interface.service';
    export class HelloEarthService implements IHelloWorldService {
        sayHi(): string;
    }
    export class MockHelloEarthService extends HelloEarthService implements IHelloWorldService {
    }
}

declare module 'hello-world-npm-module/hello-world-interface.service' {
    export interface IHelloWorldService {
        sayHi(): string;
    }
}

declare module 'hello-world-npm-module/hello-world.service' {
    import { IHelloWorldService } from 'hello-world-npm-module/hello-world-interface.service';
    export class HelloWorldService implements IHelloWorldService {
        sayHi(): string;
    }
    export class MockHelloWorldService extends HelloWorldService implements IHelloWorldService {
    }
}

