// Generated by dts-bundle v0.7.2

export class HelloAllService implements IHelloWorldService {
    constructor(helloWorld: HelloWorldService, helloEarth: HelloEarthService);
    sayHi(): string;
}
export class MockHelloAllService extends HelloAllService implements IHelloWorldService {
}

export class HelloEarthService implements IHelloWorldService {
    sayHi(): string;
}
export class MockHelloEarthService extends HelloEarthService implements IHelloWorldService {
}

export interface IHelloWorldService {
    sayHi(): string;
}

export class HelloWorldService implements IHelloWorldService {
    sayHi(): string;
}
export class MockHelloWorldService extends HelloWorldService implements IHelloWorldService {
}

